# Generated by Django 2.1.4 on 2018-12-12 00:36

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='favorited_by',
            field=models.ManyToManyField(related_name='favorite_posts', through='blog.Favorite', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='post',
            name='liked_by',
            field=models.ManyToManyField(related_name='liked_posts', through='blog.Like', to=settings.AUTH_USER_MODEL),
        ),
    ]
