# Generated by Django 2.1.4 on 2018-12-13 22:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20181212_1240'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='follow',
            unique_together={('following', 'followed')},
        ),
    ]
